import { SlashCommandBuilder, PermissionFlagsBits } from 'discord.js';
import { TRIGGER_ACTIONS, addCustomTrigger, getCustomTriggers, removeCustomTrigger } from '../../services/customTriggerService.js';
const ACTION_LABELS = {
  [TRIGGER_ACTIONS.LOCK]:'Lock current channel',[TRIGGER_ACTIONS.UNLOCK]:'Unlock current channel',[TRIGGER_ACTIONS.HIDE]:'Hide current channel',[TRIGGER_ACTIONS.UNHIDE]:'Unhide current channel',
  [TRIGGER_ACTIONS.ADD_ROLE]:'Give a role',[TRIGGER_ACTIONS.REMOVE_ROLE]:'Remove a role',[TRIGGER_ACTIONS.ADD_MEMBER]:'Add member to current channel',[TRIGGER_ACTIONS.BAN]:'Ban target',[TRIGGER_ACTIONS.KICK]:'Kick target',[TRIGGER_ACTIONS.WARN]:'Warn target',[TRIGGER_ACTIONS.MUTE]:'Mute target',[TRIGGER_ACTIONS.UNMUTE]:'Unmute target',[TRIGGER_ACTIONS.TIMEOUT]:'Timeout target (10m)',[TRIGGER_ACTIONS.UNTIMEOUT]:'Remove timeout',
};
export default { data:new SlashCommandBuilder().setName('trigger').setDescription('Create and manage word-based actions.').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild)
 .addSubcommand(s=>s.setName('add').setDescription('Create or update a word trigger.').addStringOption(o=>o.setName('word').setDescription('Exact trigger word or phrase.').setRequired(true).setMaxLength(100)).addStringOption(o=>o.setName('action').setDescription('What Orbit should do.').setRequired(true).addChoices(...Object.values(TRIGGER_ACTIONS).map(action=>({name:ACTION_LABELS[action],value:action})))).addRoleOption(o=>o.setName('role').setDescription('Role for role actions.')))
 .addSubcommand(s=>s.setName('remove').setDescription('Remove a word trigger.').addStringOption(o=>o.setName('word').setDescription('Trigger to remove.').setRequired(true).setMaxLength(100)))
 .addSubcommand(s=>s.setName('list').setDescription('Show all configured word triggers.')), category:'core',
 async execute(interaction,config,client){try{const sub=interaction.options.getSubcommand();if(sub==='add'){const word=interaction.options.getString('word',true).trim(),action=interaction.options.getString('action',true),role=interaction.options.getRole('role');if([TRIGGER_ACTIONS.ADD_ROLE,TRIGGER_ACTIONS.REMOVE_ROLE].includes(action)&&!role)return interaction.reply({content:'You must select a role for this action.',ephemeral:true});if(role?.managed)return interaction.reply({content:'That role is managed and cannot be assigned.',ephemeral:true});const bot=interaction.guild.members.me;if(role&&bot&&role.position>=bot.roles.highest.position)return interaction.reply({content:'I cannot manage that role because it is above my highest role.',ephemeral:true});const entry=await addCustomTrigger(client,interaction.guild.id,word,action,role?.id||null);return interaction.reply({content:`Trigger saved: **${entry.trigger}** → **${ACTION_LABELS[entry.action]||entry.action}**${entry.roleId?` → <@&${entry.roleId}>`:''}`,ephemeral:true});}if(sub==='remove'){const word=interaction.options.getString('word',true),removed=await removeCustomTrigger(client,interaction.guild.id,word);return interaction.reply({content:removed?`Removed trigger **${word.trim()}**.`:`No trigger was found for **${word.trim()}**.`,ephemeral:true});}const triggers=await getCustomTriggers(client,interaction.guild.id);if(!triggers.length)return interaction.reply({content:'No custom triggers are configured.',ephemeral:true});const lines=triggers.map(item=>`• **${item.trigger}** → ${ACTION_LABELS[item.action]||item.action}${item.roleId?` → <@&${item.roleId}>`:''}`);return interaction.reply({content:`**Custom Triggers (${triggers.length})**\n${lines.join('\n')}`.slice(0,2000),ephemeral:true});}catch(error){return interaction.reply({content:`Could not update triggers: ${error.message}`,ephemeral:true}).catch(()=>{});}},
};
