const games = new Map();
export const XO_JOIN_MS = 20000;
export const XO_TURN_MS = 10000;
export const XO_MAX_PLAYERS = 16;
const keyOf = (g,c) => `${g}:${c}`;
const LINES = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
function winnerOf(board){for(const [a,b,c] of LINES)if(board[a]&&board[a]===board[b]&&board[a]===board[c])return board[a];return null;}
export function createXO(guildId,channelId,starter){const key=keyOf(guildId,channelId);if(games.has(key))return{error:'active'};const game={key,guildId,channelId,participants:[starter],players:[starter],symbols:{[starter.id]:'❌'},board:Array(9).fill(null),turnIndex:0,phase:'join',active:true,tournament:true,round:1,matchIndex:0,roundWinners:[],pendingMatches:[],joinEndsAt:Math.floor((Date.now()+XO_JOIN_MS)/1000),joinTimer:null,turnTimer:null};games.set(key,game);return{game};}
export const getXO=(g,c)=>games.get(keyOf(g,c));
export const isXOPlayer=(game,id)=>!!game?.participants.some(p=>p.id===id);
export const isCurrentMatchPlayer=(game,id)=>!!game?.players.some(p=>p.id===id);
export const currentXOPlayer=game=>game?.players[game.turnIndex]||null;
export function joinXO(game,user){if(!game?.active||game.phase!=='join')return{error:'inactive'};if(isXOPlayer(game,user.id))return{error:'already'};if(game.participants.length>=XO_MAX_PLAYERS)return{error:'full'};game.participants.push(user);return{ok:true};}
export function leaveXO(game,id){if(!game?.active||game.phase!=='join')return{error:'not_in_game'};const i=game.participants.findIndex(p=>p.id===id);if(i<0)return{error:'not_in_game'};game.participants.splice(i,1);return{ok:true,empty:game.participants.length===0};}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]];}return x;}
function prepare(game,pair){game.players=pair;game.symbols={[pair[0].id]:'❌',[pair[1].id]:'⭕'};game.board=Array(9).fill(null);game.turnIndex=0;game.phase='turn';game.matchIndex++;}
function buildRound(game,players){const list=shuffle(players);game.roundWinners=[];game.pendingMatches=[];if(list.length%2)game.roundWinners.push(list.pop());for(let i=0;i<list.length;i+=2)game.pendingMatches.push([list[i],list[i+1]]);}
export function startXO(game){if(!game?.active||game.phase!=='join')return{error:'inactive'};if(game.participants.length<2)return{error:'minimum'};buildRound(game,game.participants);const pair=game.pendingMatches.shift();if(!pair)return{error:'minimum'};prepare(game,pair);return{ok:true,player:currentXOPlayer(game),round:game.round,match:game.matchIndex};}
export function pickXOCell(game,id,cell){if(!game?.active||game.phase!=='turn')return{error:'inactive'};const player=currentXOPlayer(game);if(!player||player.id!==id)return{error:'not_turn'};if(!Number.isInteger(cell)||cell<0||cell>8)return{error:'invalid_cell'};if(game.board[cell])return{error:'occupied'};game.board[cell]=game.symbols[id];const symbol=winnerOf(game.board);if(symbol){const winner=game.players.find(p=>game.symbols[p.id]===symbol)||player;const loser=game.players.find(p=>p.id!==winner.id)||null;game.phase='match_finished';return{finished:true,winner,loser,cell};}if(game.board.every(Boolean)){game.board=Array(9).fill(null);game.turnIndex=0;return{finished:false,draw:true,player:currentXOPlayer(game),next:currentXOPlayer(game),cell};}game.turnIndex=(game.turnIndex+1)%2;return{finished:false,player,next:currentXOPlayer(game),cell};}
export function timeoutXO(game){if(!game?.active||game.phase!=='turn')return null;const loser=currentXOPlayer(game);const winner=game.players.find(p=>p.id!==loser?.id)||null;game.phase='match_finished';return{loser,winner,finished:true};}
export function advanceTournament(game,winner){if(!game?.active||game.phase!=='match_finished'||!winner)return{error:'inactive'};game.roundWinners.push(winner);if(game.pendingMatches.length){const pair=game.pendingMatches.shift();prepare(game,pair);return{ok:true,match:true,round:game.round,player:currentXOPlayer(game)};}const winners=[...game.roundWinners];if(winners.length===1){game.players=winners;game.phase='tournament_finished';return{ok:true,champion:winners[0]};}game.round++;game.matchIndex=0;buildRound(game,winners);const pair=game.pendingMatches.shift();if(!pair){const champion=game.roundWinners[0];game.players=[champion];game.phase='tournament_finished';return{ok:true,champion};}prepare(game,pair);return{ok:true,match:true,round:game.round,player:currentXOPlayer(game),newRound:true};}
export function endXO(game){if(!game)return;if(game.joinTimer)clearTimeout(game.joinTimer);if(game.turnTimer)clearTimeout(game.turnTimer);game.active=false;game.phase='finished';games.delete(game.key);}
